# Generated by Django 2.0.9 on 2019-01-30 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_editing', models.BooleanField(default=False)),
                ('order_files', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
