# Generated by Django 2.0.9 on 2019-02-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20190205_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='0792799958'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='yourmail@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Peterson', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Peterson', max_length=50),
        ),
    ]
