# Generated by Django 2.0.9 on 2019-02-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20190208_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coreapp.Client'),
        ),
    ]
