# Generated by Django 2.0.13 on 2019-05-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_auto_20190429_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_files',
        ),
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
    ]
